###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID c2sgpr065.Cambridge.edu.in)
#  Generated on:      Mon Jul 27 14:18:34 2026
#  Design:            C2S0306
#  Command:           create_ccopt_clock_tree_spec -file /home/scl_shuttle_8_3/tapeout/pnr/cts/C2S0306_ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin main_clk_pad true

# Clocks present at pin main_clk_pad
#   MAIN_CLK (period 58.000ns) in timing_config all([/dev/null])
create_ccopt_clock_tree -name MAIN_CLK -source main_clk_pad -no_skew_group

# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner max_delay -early -rise -clock_tree MAIN_CLK 0.100
set_ccopt_property source_latency -delay_corner max_delay -early -fall -clock_tree MAIN_CLK 0.100
set_ccopt_property source_latency -delay_corner max_delay -late -rise -clock_tree MAIN_CLK 0.250
set_ccopt_property source_latency -delay_corner max_delay -late -fall -clock_tree MAIN_CLK 0.250
set_ccopt_property source_latency -delay_corner min_delay -early -rise -clock_tree MAIN_CLK 0.100
set_ccopt_property source_latency -delay_corner min_delay -early -fall -clock_tree MAIN_CLK 0.100
set_ccopt_property source_latency -delay_corner min_delay -late -rise -clock_tree MAIN_CLK 0.250
set_ccopt_property source_latency -delay_corner min_delay -late -fall -clock_tree MAIN_CLK 0.250
# Clock period setting for source pin of MAIN_CLK
set_ccopt_property clock_period -pin main_clk_pad 58

# Skew group to balance non generated clock:MAIN_CLK in timing_config:all (sdc /dev/null)
create_ccopt_skew_group -name MAIN_CLK/all -sources main_clk_pad -auto_sinks
set_ccopt_property include_source_latency -skew_group MAIN_CLK/all true
set_ccopt_property extracted_from_clock_name -skew_group MAIN_CLK/all MAIN_CLK
set_ccopt_property extracted_from_constraint_mode_name -skew_group MAIN_CLK/all all
set_ccopt_property extracted_from_delay_corners -skew_group MAIN_CLK/all {max_delay min_delay}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

